### ISSUE TITLE
warnings received

### ISSUE THREAD

**Issue by kjguenther** [turnermm/xtern#4]
When I run a check on external links on our wiki, I get these messages at the top of the pages where the bad links are located:
Warning: file_get_contents(): Filename cannot be empty in /home/sendu/www/www/lib/plugins/xtern/action.php on line 83

Warning: Invalid argument supplied for foreach() in /home/sendu/www/www/lib/plugins/xtern/action.php on line 84

Warning: file_get_contents(/home/sendu/www/www/data/meta/xtern/accumulator.ser): failed to open stream: No such file or directory in /home/sendu/www/www/lib/plugins/xtern/action.php on line 83

Warning: Invalid argument supplied for foreach() in /home/sendu/www/www/lib/plugins/xtern/action.php on line 84

Warning: file_get_contents(/home/sendu/www/www/data/meta/xtern/accumulator.ser): failed to open stream: No such file or directory in /home/sendu/www/www/lib/plugins/xtern/action.php on line 83

Warning: Invalid argument supplied for foreach() in /home/sendu/www/www/lib/plugins/xtern/action.php on line 84

Warning: Cannot modify header information - headers already sent by (output started at /home/sendu/www/www/lib/plugins/xtern/action.php:83) in /home/sendu/www/www/lib/plugins/ckgedit/action/meta.php on line 712

Warning: Cannot modify header information - headers already sent by (output started at /home/sendu/www/www/lib/plugins/xtern/action.php:83) in /home/sendu/www/www/lib/plugins/ckgedit/action/meta.php on line 714

Warning: Cannot modify header information - headers already sent by (output started at /home/sendu/www/www/lib/plugins/xtern/action.php:83) in /home/sendu/www/www/lib/plugins/ckgedit/action/meta.php on line 715

Warning: Cannot modify header information - headers already sent by (output started at /home/sendu/www/www/lib/plugins/xtern/action.php:83) in /home/sendu/www/www/lib/plugins/ckgedit/action/meta.php on line 810

Warning: file_get_contents(/home/sendu/www/www/data/meta/xtern/accumulator.ser): failed to open stream: No such file or directory in /home/sendu/www/www/lib/plugins/xtern/action.php on line 83

Warning: Invalid argument supplied for foreach() in /home/sendu/www/www/lib/plugins/xtern/action.php on line 84

Warning: Cannot modify header information - headers already sent by (output started at /home/sendu/www/www/lib/plugins/xtern/action.php:83) in /home/sendu/www/www/inc/actions.php on line 38

Warning: Cannot modify header information - headers already sent by (output started at /home/sendu/www/www/lib/plugins/xtern/action.php:83) in /home/sendu/www/www/lib/tpl/dokuwiki/main.php on line 12

**Comment by turnermm** [comment]
I've put in a check, so download the latest.  _ assume you are using the xtern admin app?_

**Comment by kjguenther** [comment]
Yes, I am using the xtern admin app. I updated the plug-in. Now there are no error messages. But I also do not see the broken links at the top of the page in yellow message banners. All I see is just the page opened in edit mode.
"When the new window opens for editing, the broken links for this page will be displayed at the top of the page in yellow message banners. In the file itself, the broken links will be marked as broken:"

**Comment by turnermm** [comment]
If you have the latest version (4/17) and have run the admin xtern app, you should see the yellow warnings and the broken link markup.  Make sure you have the following file in the meta/xtern directory:  `accumulator.ser`
Attached is a small capture of a test I just made using the current version.

![xtern_eg](https://user-images.githubusercontent.com/176447/58031830-e08e4e00-7ae6-11e9-8671-362ec8b9b174.png)

**Comment by kjguenther** [comment]
I have uninstalled the extension, and reinstalled it. The file
accumulator.ser file does not exist, and neither does the meta/xtern
directory. What do I do now?

**Comment by kjguenther** [comment]
By the way, whenever we have run the admin xtern app, it never completes the search to the end. It stops about 75% of the way through. Is that I am not seeing the error messages at the top of the page?

**Comment by kjguenther** [comment]
OK, I just ran the admin xtern app on a namespace that is smaller in size. When it completed, I did see the broken list at the top in yellow and I found the accumulator.ser file in the meta/xtern directory.  There was no broken link mark-up in the text of the page though.

**Comment by kjguenther** [comment]
OK, I just ran the admin xtern app on a namespace that is smaller in size. When it completed, I did see the broken list at the top in yellow and I found the accumulator.ser file in the meta/xtern directory. A few of the broken links were marked in the text, but not nearly all of them.

**Comment by turnermm** [comment]
Try increasing the max_time configuration setting

**Comment by kjguenther** [comment]
I increased it to 200 but it still ended at the same place. I got this message: Fatal error: Out of memory (allocated 42467328) (tried to allocate 33557426 bytes) in /home/sendu/www/www/lib/plugins/xtern/admin.php on line 269

**Comment by turnermm** [comment]
Try increasing your memory limit in php.ini.  Otherwise, you don't have the resources for the size of your web site and there's really  nothing I can do for that.  You will have to do it namespace by namespace.

**Comment by turnermm** [comment]
The current default memory limit is 128mb.  What your error message says is that you have run out of memory at about 75 mb.  You can increase it with the memory_limit setting.  If you have permission to do this, you can do  so in php.ini.

**Comment by kjguenther** [comment]
My memory_limit setting is set at 200M.  Are you saying it should be set at higher than that?

post_max_size = 20M
memory_limit = 200M
upload_max_filesize = 20M
max_execution_time = 120

**Comment by turnermm** [comment]
Create an index  script with phpinfo():  
```
 <php 
 phpinfo()
 ?>
```
Put it in the directory where you have you have your wiki and run it from your browser,.  Under Core, check the memory limit.  I'm not a php error message expert, but from what I can read in  your error message, the server has allotted 42.5 megabytes for this script and has tried to allocate another 33.5, but has no memory left.  The 200M is supposed to be a per script limit, but this adds up to 76.  Where is your server?  Are you on a hosting service?

**Comment by kjguenther** [comment]
I contacted support on my server, and they fixed the problem. Thanks.
