### ISSUE TITLE
malformed URL lookups

### ISSUE THREAD

**Issue by mekineer** [turnermm/xtern#7]
I got a lot of false 404 links, because Xtern is not truncating the URL correctly.  For example:

(https://en.wikipedia.org/wiki/Crop_diversity)

Xtern is looking for https://en.wikipedia.org/wiki/Crop_diversity)  <- parenthesis shouldn't be there

https://en.wikipedia.org/wiki/Crop_diversity\\

Xtern is looking for https://en.wikipedia.org/wiki/Crop_diversity\\  <- newline \\ markup shouldn't be there

**Comment by turnermm** [comment]
The fix is now included in the latest update, so you can just re-install from the extension manager.  Please let me know if it continues to give you problems or if any other similar issues occur.

**Comment by mekineer** [comment]
Thanks.  I updated and it's working now.  :-)

**Comment by turnermm** [comment]
I updated the plugin this morning to accommodate  punctuation characters as well as  `)` and `\\`.
